---

- name: Provision a DEBUG-ADS-1 {{ application_name }} db server
  hosts: dbservers
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - db
